---
info:
  component: Default Single Swagger Document Server for MicroService

spring:
  profiles: default

server:
  port: 8014

documentation: 
  baseurl: http://localhost
  swagger: 
    services:   
      - 
        name: Shop
        url: http://ec2-18-191-27-130.us-east-2.compute.amazonaws.com:8081/v2/api-docs?group=shop
        version: 2.0
      -
        name: Sales
        url: http://ec2-18-219-254-63.us-east-2.compute.amazonaws.com:8082/v2/api-docs?group=sales
        version: 2.0